ARG centos=7.9.2009
FROM aursu/rpmbuild:${centos}-build

USER root
RUN yum -y install \
        expat-devel \
        openssl-devel \
        perl-generators \
        systemd-devel \
        xmlto \
        zlib-devel \
    && yum clean all && rm -rf /var/cache/yum
