FROM aursu/rpmbuild:6-build

USER root
RUN yum -y install \
        expat-devel \
        openssl-devel \
        pcre-devel \
        perl-generators \
        xmlto \
        zlib-devel \
    && yum clean all && rm -rf /var/cache/yum
