ARG centos=6.10
FROM aursu/rpmbuild:${centos}-build

USER root
RUN yum -y install \
        expat-devel \
        openssl-devel \
        pcre-devel \
        perl-generators \
        xmlto \
        zlib-devel \
    && yum clean all && rm -rf /var/cache/yum
