FROM aursu/rpmbuild:7-build

USER root
RUN yum -y install \
        expat-devel \
        openssl-devel \
        perl-generators \
        systemd-devel \
        xmlto \
        zlib-devel \
    && yum clean all && rm -rf /var/cache/yum
